### ISSUE TITLE
New data indicator for AOIs

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#24]
@AlexMountain @trevorskaggs We have talked about webhooks or similar to notify users of new data in an AOI, which is great, but GRiD is **already** able to flag AOIs that have "New data". How is this obtained? Can it be exposed via the API? If so, what is the best way? As a flag attached to individual intersects? As it's own (possibly empty) array of intersecting pks (with further information available in the intersect objects)?

**Comment by AlexMountain** [comment]
This could be exposed to the API with some tweaks.  We determine this for any aoi_detail call.  The new data flag is at the individual intersect level, so a flag there would probably be the easiest/most direct approach.

We would need to revise the clearing away of the "new data" designation that also works with the API.  For the UI this happens when you navigate to the respective generate export screen, but maybe for the API we mark as viewed after the aoi_detail return.

**Comment by AlexMountain** [comment]
AOI GET requests now return a list product IDs for new data loaded, one time (will not show up in subsequent GET requests to the same AOI). Docs are updated to reflect this.
