### ISSUE TITLE
Document potential or acceptable values where possible

### ISSUE THREAD

**Issue by jw3** [CRREL/GRiD-API#30]
1. In v2 and v3 the value of the `Status` object is documented in multiple places as
>(e.g., SUCCESS, FAILED, QUEUED)

2. In v3 the `event` for a Hook is documented as
>(e.g. export.complete, newdata.loaded)

Having the set of potential values for (1) and acceptable values for (2) would be useful.  If I've overlooked it please advise.

As of now for (1) we are tracking possible values as

- SUCCESS
- RUNNING
- QUEUED
- FAILED
- CANCELED

**Comment by AlexMountain** [comment]
There's only two events at the moment, so that list is all of them.  Your task status list looks comprehensive as well.

Technically we are serving back the list of acceptable values if you sent us a bad one, but you're right, it makes way more sense to just provide you with the proper acceptable values to pass up front.

**Comment by AlexMountain** [comment]
Updated v3 docs to include all valid parameters limited to a set list.
